#!/usr/bin/env python3

import argparse
import os
import utils
import templ

def create_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="The toolkit for livepatch developers")

    sub = parser.add_subparsers(dest="command")
    setup = sub.add_parser('setup-bsc')
    setup.add_argument('-d', '--dest', type=str, default='',
            help='Destination directory to build livepatches')
    setup.add_argument('--redownload', action='store_true',
            help='Replaces the currently used codestream.in file')
    setup.add_argument('--bsc', type=str, required=True,
            help='The bsc number related to this livepatch. This will be the directory name of the resulting livepatches')
    setup.add_argument('--cve', type=str, required=True,
            help='The CVE assigned to this livepatch')
    setup.add_argument('--conf', type=str, required=True,
            help='The kernel CONFIG used to be build the livepatch')
    setup.add_argument('--file', type=str, required=True,
            help='File that containes the function to be livepatched')
    setup.add_argument('--func', type=str, required=True,
            help='Function to the livepatched')
    setup.add_argument('-m', '--module', type=str,
            help='The module that will be livepatched')

    templ = sub.add_parser('create-lp')
    templ.add_argument('--bsc', type=str, requred=True,
            help='The bsc number related to this livepatch. This will be the directory name of the resulting livepatches')
    templ.add_argument('-t', '--type', type=str, required=True,
            help='The livepatch type, being kgraft (kgr) or klp', choices=['klp', 'kgr'])
    return parser

if  __name__ == '__main__':
    parser = create_parser()
    args = parser.parse_args()

    if args.command == 'setup-bsc':
        setup = utils.Setup(args.dest, args.redownload, args.bsc, args.cve,
                            args.conf, args.file, args.func, args.module)
        setup.prepare_env()
    elif args.command == 'create-lp':
        templ = templ.Template(args.bsc, args.type)
        templ.GenerateLivePatches()
