.\" SPDX-License-Identifier: GPL-2.0-only
.\"
.\" Copyright (C) 2021-2024 SUSE
.\" Author: Fernando Gonzalez <fernando.gonzalez@suse.com>
.\"

.TH klp-build 1
.SH NAME
klp-build \- the kernel livepatching creation tool
.SH SYNOPSIS
.B klp-build
[-h] [-v] [-V]
<command> [-h] [-n NAME] [--filter FILTER]
.SH DESCRIPTION
.B klp-build
is a tool meant for automating the whole process of creating and testing
livepatches for the Linux kernel (SLE edition).
To reduce the burden of livepatch developement,
.B klp-build
is also capable of checking which codestreams are vulnerable, batching multiple
codestreams in parallel, and remotely building and running tests.
.SH OPTIONS
Generic options available for all commands:
.TP
.B "-h, --help"
Show command's help message and exit.
.TP
.B "-v, --verbose"
Produce more verbose output.
.TP
.BI "-n, --name" " NAME"
The livepatch name. This will be the directory name of the resulting
livepatches.
.TP
.BI --filter " FILTER"
List of accepted codestreams. Must be specified in regex format.
Example: '15\.3u[0-9]+|15\.6u0'
.br
You can also use a negative regex in order to filter out a specific codestream.
Example: '^(?!12.5u12).*'
.TP
.B -V, --version
show
.BR klp-build 's
version number and exit.
.SH COMMANDS
.TP
.B data
Manage codestreams data.
.RS 7
.TP
.B --download
Download all the missing supported codestreams data.
.TP
.B --force
Re-download also codestream that are not missing.
.RE
.TP
.B scan
In the scan,
.B klp-build
does a shallow analysis of the given CVE, searching for already patched codestreams
and reporting those that most likley are still affected by the bug.
This subcommand does not store any data, as it is mainly targeted for automation
and not for livepatch development. For the latter see the
.B setup
subcommand.
.RS 7
.TP
.BI --cve " CVE"
The CVE to be analyzed.
.TP
.B --download
Download missing codestreams data.
.RE
.TP
.B setup
During the setup,
.B klp-build
analysis each codestream in order to identify those affected by
the indicated CVE. Note that in this phase a lot of per-codestream
data is generated and stored for future use.
.RS 7
.TP
.BI --cve " CVE"
The CVE assigned to this livepatch.
.TP
.BI --conf " CONF"
The kernel CONFIG used to build the object to be livepatched.
.TP
.B --no-check
Do not check for already patched codestreams, do the setup for
all non filtered codestreams.
.TP
.BI --codestreams " CODESTREAMS"
Codestreams affected by the CVE. Can be used as a regex, like,
"15.u[34]".
.TP
.BI --file-funcs " [FILE_FUNCS ...]"
File and functions to be livepatched. Can be set multiple times. The format is:
.BI --file-funcs " file/path.c func1 func2..."
.BI --file-funcs " file/patch2.c func1 func2..."
.TP
.BI --mod-file-funcs " [MOD_FILE_FUNCS ...]"
Module, file and functions to be livepatched. Can be set multiple times. The
format is:
.BI --mod-file-funcs " module1 file/path.c func1 func2..."
.BI --mod-file-funcs " module2 file/patch2.c func1 func2..."
.TP
.BI --conf-mod-file-funcs " [CONF_MOD_FILE_FUNCS ...]"
Conf, module, file and functions to be livepatched. Can be set multiple times.
The format is:
.BI --conf-mod-file-funcs " conf1 module1 file/path.c func1 func2..."
.BI --conf-mod-file-funcs " conf2 module2 file/patch2.c func1 func2..."
.TP
.BI --module " MODULE"
The module that will be livepatched for all files. If empty,
.I vmlinux
will be livepatched instead.
.TP
.BI --archs " {ppc64le,s390x,x86_64} [{ppc64le,s390x,x86_64} ...]"
Supported architectures for this livepatch.
.RE
.TP
.B extract
In this phase
.B klp-build
creates the livepatch for each affected codestream based on the data generated
during the
.BR setup "."
Results may differ greatly depending on the back-end tool selected for the
livepatch creation.
.RS 7
.TP
.BI --avoid-ext " AVOID_EXT [AVOID_EXT ...]"
Functions to be copied into the livepatch instead of externalizing them.
Useful to make sure to include symbols that are optimized in
different architectures.
.TP
.B --apply-patches
Apply patches if they exist.
.TP
.BI --codestreams " CODESTREAMS CODESTREAMS"
Apply diff on two different codestreams.
.RE
.TP
.B format-patches
Extract patches from kgraft-patches (see the
.BR "SEE ALSO" " section)."
.RS 7
.TP
.BI "-v , --version" " VERSION"
Version to be added, like vX.
.RE
.TP
.B cs-diff
Compare line by line the output livepatch of two codestreams.
.RE
.TP
.B cleanup
Remove livepatch packages from SUSE's Build Service.
.TP
.B prepare-tests
Generates a tar archive per supported architecture containing
scripts and files that can later be used to run tests in the desired test benchs.
.TP
.B push
Push the generated livetpatch packages to SUSE's Build Service.
By doing so,
.B klp-build
can automate the building phase for each codestream and architecture.
.RS 7
.TP
.B --wait
Wait until all codestreams builds are finished.
.RE
.TP
.B status
Check the status of the livepatch building phase initiated by the
.B push
command.
.RS 7
.TP
.B --wait
Wait until all codestreams builds are finished.
.RE
.TP
.B log
Get build logs from SUSE'S Build Service.
.RS 7
.TP
.BI --arch " {ppc64le,s390x,x86_64}"
Build architecture.
.TP
.BI --filter
Required. Needs to specify only specific codestream.
.RE
.SH FILES
.TP
.I ~/.config/klp-build/config
Personal configuration file
.TP
.I ~/klp/livepatches
Default directory where the livepatch data will be
placed, including the data generated by the different stages of the livepatch
creation
.TP
.I ~/klp/data
Default directory where the dowloaded source code will be placed
.SH EXAMPLES
Check if the codestreams for SLE 15.5 x86_64 and ppc64le are affected by
CVE-2022-1048. This CVE affects
.I snd_pcm_attach_substream()
and
.I snd_pcm_detach_substream()
functions, located in the
kernel module
.IR snd-pcm .
.IP
$
.B klp-build
setup --name bsc1197597 --cve 2022-1048 --mod snd-pcm --conf
CONFIG_SND_PCM --file-funcs sound/core/pcm.c snd_pcm_attach_substream
snd_pcm_detach_substream --codestreams '15.5' --archs x86_64 ppc64le
.PP
Compare two codestreams:
.IP
$
.B klp-build
cs-diff -n bsc1197597 --filter '15.5u0|15.5u1'
.PP
.SH SEE ALSO
SUSE's kgraft-patches public repository:
.I https://github.com/SUSE/kernel-livepatch
.PP
SUSE's kernel-source public repository:
.I https://github.com/SUSE/kernel-source
.PP
.BR klp-ccp "(1) "
.SH AUTHOR
Contributors to the
.B klp-build
project. See the project’s GIT history for the complete list.
.SH DISTRIBUTION
The latest version of
.B klp-build
may be downloaded from https://github.com/SUSE/klp-build
